[package]
name = "sendai"
version = "0.1.0"
authors = ["Micah Johnston <micah@glowcoil.com>"]
edition = "2018"

[dependencies]
gl = "0.11.0"
glfw = "0.34.0"
gouache = { git = "https://github.com/glowcoil/gouache" }
